### ISSUE TITLE
pipx run is not working

### ISSUE THREAD

**Issue by jgd10** [pyansys/create-python-project#56]
Using the latest development version pipx does not run. I get the following error:

![image](https://user-images.githubusercontent.com/12530336/155298843-72b2f9e6-ed63-4dfc-b312-3ee0d829e9ef.png)

but using pip _does_ work

![image](https://user-images.githubusercontent.com/12530336/155298951-ed6282a7-9531-47b4-8bd2-105b9f143bb4.png)

**Comment by nick-marnik** [comment]
Per the docs, I tried using `acpp` for the package name, but I get this error:
```
pipx run acpp -n my-project
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\nmarnik\.local\pipx\logs\cmd_2022-03-16_13.21.57_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement acpp (from versions: none)
    ERROR: No matching distribution found for acpp
Error installing acpp.
```

The log file generated doesn't offer much more info:
```
PIP STDOUT
----------

PIP STDERR
----------
ERROR: Could not find a version that satisfies the requirement acpp (from versions: none)
ERROR: No matching distribution found for acpp

```

**Comment by jgd10** [comment]
It looks like the reason for this error is because of the alias "acpp", and essentially pipx can not handle the fact that the package name and the run command are different (it tries to use the same one). I am currently investigating this because I think "ansys-create-python-project" is too long as a package name to be typed out but "acpp" is not unique enough to be the name on its own.

**Comment by jgd10** [comment]
This can be fixed using entry points, I think. I am working on a PR at the moment.
